version: '3'

volumes:
  keycloak_pg_data:
    driver: local

services:
  keycloak-db:
    image: 'postgres:12.9'
    volumes:
      - keycloak_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpassword

  keycloak:
    image: 'apicurio/apicurio-studio-auth:16.1.0'
    depends_on: [keycloak-db]
    ports:
      - '8090:8080'
    environment:
      APICURIO_KEYCLOAK_USER: admin
      APICURIO_KEYCLOAK_PASSWORD: admin123
      APICURIO_UI_URL: http://localhost:8888
      DB_VENDOR: postgresql
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: pgadmin
      DB_PASSWORD: pgpassword

